language: python
python:
  - 2.7
# Need to set this so that packages installed with apt-get are available
virtualenv:
  system_site_packages: true
before_install:
  - sudo apt-get -qq update
  - sudo apt-get -qq install python-dev python-imaging python-numpy python-scipy python-matplotlib
  - pip install -q --use-mirrors nose sphinx coverage coveralls
# Build the docs before installing because sphinx breaks on Cython modules
  - cd doc; sphinx-build -W -d _build/doctrees -b html . _build/html; cd ..
install:
  - python setup.py build_ext --inplace
script:
  - nosetests fatiando test -v --with-doctest --with-coverage --cover-package=fatiando
after_success:
  - coveralls
notifications:
  email: false
