language: python
python:
  - 2.7
install:
  - sudo apt-get -qq install cython python-dev python-numexpr python-imaging python-numpy python-scipy python-matplotlib mayavi2 
  - pip install -q --use-mirrors nose
  - python setup.py build
  - pip install --use-mirrors .
script:
  - make test
notifications:
  email: false
