language: python
python:
  - 2.7
virtualenv:
  system_site_packages: true
install:
  - sudo apt-get -qq install python-dev python-numexpr python-imaging python-numpy python-scipy python-matplotlib mayavi2 
  - pip install -q --use-mirrors nose cython
  - pip install --use-mirrors .
  - python setup.py build_ext --inplace
script:
  - nosetests fatiando -v --with-doctest # Run the doctests
  - nosetests test -v # Run the unit tests
notifications:
  email: false
